services:
  app:
    image: node:20
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "8090:8090"
    command: "sh -c 'npm i --no-audit && sleep 20 && node init.js && node app.js'"
    environment:
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: myapp
    depends_on:
      - db
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: ChefDB
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
